### PR TITLE
Quiz: answer question

### PR DESCRIPTION
**Pull request by robinmessage**
Getting there, you can now actually answer questions...

I'm not 100% happy with `ResponseWrapper`; as `SegueResponse` itself says, maybe it should be an exception or a Throwable. But it very much felt like I wanted exceptional control flow and didn't want to make significant changes to the logic of existing code.

---

**Pull Request Check List**
- [ ? ] Added enough Logging to monitor expected behaviour change
- [x] Security - Injection - everything run by an interpreter (SQL, OS...) is either validated or escaped
- [x] Security - Data Exposure - PII is not stored or sent unencrypted
- [x] Security - Data Exposure - Test any altered or created endpoints using [swagger](http://localhost:8080/isaac-api/api-docs/)
- [x] Security - Access Control - Check authorisation on every new endpoint
- [ ] DB schema changes - postgres-rutherford-create-script updated
- [ ] DB schema changes - upgrade script created matching create script
- [ ] Updated Release Procedure & Documentation (& Considered Implications to Previous Versions)
- [ ] Peer-Reviewed

### CODE REVIEW

**Review by jsharkey13 — APPROVED** [review]
The detail of this all looks good. I wonder if @mlt47 has opinions on the ResponseWrapper exception class?

**Comment by mlt47** [comment]
> The detail of this all looks good. I wonder if @mlt47 has opinions on the ResponseWrapper exception class?

I can see the usefulness of the ResponseWrapper for doing a similar job to what the suggested refactor would do. I'm happy with doing that in the Facades. I would slightly prefer not using it in the managers so that the managers don't need to know about responses and requests but, as there are already many manager methods that are returning responses, that is OK with me for now.

**Comment by mlt47** [comment]
> > The detail of this all looks good. I wonder if @mlt47 has opinions on the ResponseWrapper exception class?
> 
> I can see the usefulness of the ResponseWrapper for doing a similar job to what the suggested refactor would do. I'm happy with doing that in the Facades. I would slightly prefer not using it in the managers so that the managers don't need to know about responses and requests but, as there are already many manager methods that are returning responses, that is OK with me for now.

Let's rename it to ErrorResponseWrapper or something to differentiate it from ResultsWrapper

**Comment by robinmessage** [comment]
@mlt47 Renaming to `ErrorResponseWrapper` sounds good to me, I'll do that.

**Pull request merged**
