### PR TITLE
Quiz: get assigned quizzes

### PR DESCRIPTION
**Pull request by robinmessage**
---

**Pull Request Check List**
- [ ] Unit Tests & Regression Tests Added (Optional)
- [ :+1: ] Removed Unnecessary Logs/System.Outs/Comments/TODOs
- [ :+1: ] Added enough Logging to monitor expected behaviour change
- [ :+1: ] Security - Injection - everything run by an interpreter (SQL, OS...) is either validated or escaped
- [ :+1: ] Security - Data Exposure - PII is not stored or sent unencrypted
- [ :+1: ] Security - Data Exposure - Test any altered or created endpoints using [swagger](http://localhost:8080/isaac-api/api-docs/)
- [ :+1: ] Security - Access Control - Check authorisation on every new endpoint
- [ N/A ] Security - New dependency - configured sensibly not relying on defaults
- [ N/A ] Security - New dependency - Searched for any know vulnerabilities
- [ N/A ] Security - New dependency - Signed up team to mailing list
- [ N/A ] Security - New dependency - Added to dependency list
- [ N/A ] DB schema changes - postgres-rutherford-create-script updated
- [ N/A ] DB schema changes - upgrade script created matching create script
- [ N/A ] Updated Release Procedure & Documentation (& Considered Implications to Previous Versions)
- [ ] Peer-Reviewed

### CODE REVIEW

**Review by jsharkey13 — APPROVED** [review]
GitHub won't show the diff between this and `master`, only the full branch diff. It is possible to only [show the relevant diff using the compare tool](https://github.com/isaacphysics/isaac-api/compare/master...robinmessage-quiz-getAssignedQuizzes), but I can't comment on anything that way. It's a pain!

There seem to be some unused imports, and I don't quite understand the Guice stuff to know why `asEagerSingleton` is right or necessary, but otherwise I think it looks fine!

**Comment by robinmessage** [comment]
> GitHub won't show the diff between this and `master`, only the full branch diff. It is possible to only [show the relevant diff using the compare tool](https://github.com/isaacphysics/isaac-api/compare/master...robinmessage-quiz-getAssignedQuizzes), but I can't comment on anything that way. It's a pain!

I've beaten it into submission now. I think I missed a rebase earlier.
 
> There seem to be some unused imports, and I don't quite understand the Guice stuff to know why `asEagerSingleton` is right or necessary, but otherwise I think it looks fine!

Ah, maybe I need to add a comment to the Guide stuff? We need an Eager Singleton as no-one actually injects the listener, so without that it wouldn't actually get constructed.

**Comment by jsharkey13** [comment]
There was actually a comment on the line in question, I just don't know enough about Guice! I think the existing comment is fine.

Not sure I'm a fan of the force-pushing, but it does make it easier to review!

**Comment by robinmessage** [comment]
> There was actually a comment on the line in question, I just don't know enough about Guice! I think the existing comment is fine.

Great.
 
> Not sure I'm a fan of the force-pushing, but it does make it easier to review!

Well, in a distributed development process it is bad. But these are my branches (I even put my name on them) so as far as I can see the force push is perfectly safe and keeps the history clean. And indeed makes review better. Although I just remembered, from the files changed view you can pick a range of commits I think?

**Review by mlt47 — APPROVED** [review]
This is nice 👍

**Review by jsharkey13 — APPROVED** [review]

**Pull request merged**
